/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface OptionConfig {
  name: string
}

export declare export declare function parser(content: string, config: ParserConfig): Record<string, string>

export interface ParserConfig {
  options: Array<OptionConfig>
  prefixes: Array<string>
  separators: Array<string>
  quotes: Array<Array<string>>
}

